-- Création de la base de données
CREATE DATABASE IF NOT EXISTS mcd;
USE mcd;

-- =================================================================================
-- TABLES AVEC IDENTIFIANTS ISSUS DE LA SOURCE (Clés Primaires Naturelles)
-- =================================================================================

CREATE TABLE Ressource (
    ID_RESSOURCE INT PRIMARY KEY,
    NOM_RESSOURCE VARCHAR(255)
);

CREATE TABLE Piece (
    ID_PIECE INT PRIMARY KEY,
    DESCRIPTION_PIECE VARCHAR(255)
);

CREATE TABLE Operation (
    ID_OPERATION INT PRIMARY KEY,
    DESCRIPTION_OPERATION VARCHAR(255)
);

CREATE TABLE Erreur (
    ID_ERREUR INT PRIMARY KEY,
    DESCRIPTION_ERREUR VARCHAR(255)
);

CREATE TABLE Commande (
    ID_COMMANDE INT PRIMARY KEY,
    DATE_DEBUT_COMMANDE DATETIME,
    DATE_FIN_COMMANDE DATETIME,
    DATE_FIN_PLANIFIEE_COMMANDE DATETIME
);

CREATE TABLE Buffer (
    ID_RESSOURCE INT,
    ID_BUFFER INT,
    CAPACITE_TOTALE INT,
    PRIMARY KEY (ID_RESSOURCE, ID_BUFFER),
    FOREIGN KEY (ID_RESSOURCE) REFERENCES Ressource(ID_RESSOURCE)
);

-- =================================================================================
-- TABLES AVEC IDENTIFIANTS GÉNÉRÉS AUTOMATIQUEMENT (Clés Primaires Techniques)
-- =================================================================================

CREATE TABLE Production_operations (
    ID_PRODUCTION_OPERATIONS INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMMANDE INT,
    ID_PIECE INT,
    ID_RESSOURCE INT,
    ID_OPERATION INT,
    ETAPE_DEBUT DATETIME,
    ETAPE_FIN DATETIME,
    ETAPE_EST_CONFORME BOOLEAN,
    STOCK_CAPACITE_TOTALE INT,
    STOCK_POSITIONS_OCCUPEES INT,
    STOCK_QUANTITE_STOCK INT,
    ID_ERREUR INT,
    FOREIGN KEY (ID_COMMANDE) REFERENCES Commande(ID_COMMANDE),
    FOREIGN KEY (ID_PIECE) REFERENCES Piece(ID_PIECE),
    FOREIGN KEY (ID_RESSOURCE) REFERENCES Ressource(ID_RESSOURCE),
    FOREIGN KEY (ID_OPERATION) REFERENCES Operation(ID_OPERATION),
    FOREIGN KEY (ID_ERREUR) REFERENCES Erreur(ID_ERREUR),
    UNIQUE (ID_COMMANDE, ID_OPERATION, ETAPE_DEBUT)
);

CREATE TABLE Surveillance_machine (
    ID_SURVEILLANCE_MACHINE INT AUTO_INCREMENT PRIMARY KEY,
    ID_RESSOURCE INT,
    ETAT_MACHINE_HORODATAGE DATETIME,
    ETAT_MACHINE_EN_MARCHE BOOLEAN,
    ETAT_MACHINE_EN_ARRET BOOLEAN,
    ETAT_MACHINE_RESET BOOLEAN,
    FOREIGN KEY (ID_RESSOURCE) REFERENCES Ressource(ID_RESSOURCE),
    UNIQUE (ID_RESSOURCE, ETAT_MACHINE_HORODATAGE)
);

CREATE TABLE CONTENU_STOCK (
    ID_CONTENU INT AUTO_INCREMENT PRIMARY KEY,
    ID_RESSOURCE INT,
    ID_BUFFER INT,
    ID_PIECE INT,
    QUANTITE INT,
    NUM_EMPLACEMENT INT,
    FOREIGN KEY (ID_RESSOURCE, ID_BUFFER) REFERENCES Buffer(ID_RESSOURCE, ID_BUFFER),
    FOREIGN KEY (ID_PIECE) REFERENCES Piece(ID_PIECE),
    UNIQUE (ID_RESSOURCE, ID_BUFFER, ID_PIECE, NUM_EMPLACEMENT)
);
